CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) not null unique,
    login varchar(30) not null unique,
    name varchar(30),
    birthday date
);

CREATE TABLE IF NOT EXISTS mpa_ratings (
    id integer generated by default as identity primary key,
    rating varchar(20) not null
);

CREATE TABLE IF NOT EXISTS genres (
    id integer generated by default as identity primary key,
    name varchar(50) not null
);

CREATE TABLE IF NOT EXISTS friendship_status (
    id integer generated by default as identity primary key,
    name varchar(30) not null
);

CREATE TABLE IF NOT EXISTS films (
    id integer generated by default as identity primary key,
    name varchar(60) not null,
    description varchar(200),
    release_date date not null,
    duration integer not null,
    mpa_rating integer not null references mpa_ratings(id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id integer not null references films(id),
    genre_id integer not null references genres(id),
    primary key (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friendships (
    user_id integer not null references users(id),
    friend_id integer not null references users(id),
    status integer not null references friendship_status(id),
    created_at timestamp not null,
    primary key (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id integer not null references films(id),
    user_id integer not null references users(id),
    created_at timestamp not null,
    primary key (film_id, user_id)
);